### ISSUE TITLE
Bug while finding language

### ISSUE THREAD

**Issue by koenedaele** [koenedaele/skosprovider#29]
Following problem occurs when running an example from skosprovider_getty.

```bash
[17:05:06] $ python churches.py 
Label per language
------------------
en --> en: churches (buildings) [prefLabel]
nl --> nl: kerken [prefLabel]
es --> es: iglesias [prefLabel]
de --> de: kirchen (Gebäude) [prefLabel]
Traceback (most recent call last):
  File "churches.py", line 19, in <module>
    label = churches.label(l)
  File "/home/koen/Virtualenvs/skosprovider_getty/local/lib/python2.7/site-packages/skosprovider/skos.py", line 367, in label
    return label(self.labels, language)
  File "/home/koen/Virtualenvs/skosprovider_getty/local/lib/python2.7/site-packages/skosprovider/skos.py", line 524, in label
    l = find_best_label_for_type(labels, language, 'prefLabel')
  File "/home/koen/Virtualenvs/skosprovider_getty/local/lib/python2.7/site-packages/skosprovider/skos.py", line 549, in find_best_label_for_type
    inexact = filter_labels_by_language(typelabels, language, True)
  File "/home/koen/Virtualenvs/skosprovider_getty/local/lib/python2.7/site-packages/skosprovider/skos.py", line 568, in filter_labels_by_language
    return [l for l in labels if tags.tag(l.language).language.format == language]
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by koenedaele** [comment]
Problem happend with `zh-hant` because that's a redundant tag (see OnroerendErfgoed/language_tags#10). Had an older version of language-tags in my virtualenv.
